os: windows
language: bash

install:
  - '[ -d "/c/Python37" ] || choco install python --version 3.7.3 --x86'
  - /c/Python37/Scripts/pip install -r requirements.txt
  - /c/Python37/Scripts/pip install pyinstaller

script:
  - /c/Python37/Scripts/pyinstaller --onefile --noconsole --add-data="*.ui;." --name="padmiss-daemon" gui.py

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN" # insert one here.
  file: "dist/padmiss-daemon.exe"
  skip_cleanup: true
  draft: true

cache:
  directories:
    - /c/Python37
